version: "3"

services:
  database:
    image: mysql:latest
    container_name: database
    networks:
      - local
    environment:
      MYSQL_USER: test
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: slfjslfsidjfsldkfjldskf
    # https://github.com/docker-library/wordpress/issues/313
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    networks:
      - local
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress

networks:
  local:
    external: true
